[program:tdg-worker-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/tdg-marketing/artisan queue:work redis --queue=default --sleep=1 --tries=3 --timeout=960 --max-time=3600 --max-jobs=200
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=deploy
numprocs=4
startsecs=2
stopwaitsecs=960
redirect_stderr=true
stdout_logfile=/var/log/tdg-marketing/worker-default.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
