[program:tdg-worker-email]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/tdg-marketing/artisan queue:work redis --queue=email --sleep=1 --tries=1 --timeout=420 --max-time=3600 --max-jobs=50
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=deploy
numprocs=2
startsecs=2
stopwaitsecs=420
redirect_stderr=true
stdout_logfile=/var/log/tdg-marketing/worker-email.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
